const AWG={14:2.525,12:1.588,10:0.9989,8:0.6282,6:0.3951,4:0.2485,2:0.1563};
function voltageDrop(){const amps=+document.querySelector('#amps').value,feet=+document.querySelector('#feet').value,volts=+document.querySelector('#volts').value,awg=document.querySelector('#awg').value,phase=document.querySelector('#phase').value;const drop=(phase==='3'?1.732:2)*(AWG[awg]*feet/1000)*amps;const pct=drop/volts*100;document.querySelector('#vdrop').innerHTML='<strong>'+drop.toFixed(2)+' V</strong> · '+pct.toFixed(2)+'% of '+volts+' V<br><span class="'+(pct>3?'warn':'ok')+'">'+(pct>3?'Above a common 3% branch-circuit planning target. Upsize the wire or shorten the run.':'Inside a common 3% branch-circuit planning target.')+'</span><br>Copper approximate DC resistance only. Not a code calculation or stamp.';}
const planets=[{a:46,speed:.017,color:'#c9b7a2'},{a:72,speed:.012,color:'#e0c07a'},{a:98,speed:.01,color:'#6f9e78'},{a:128,speed:.008,color:'#c4654a'},{a:168,speed:.0044,color:'#d7b48a'}];
let orbitOn=true;function drawOrbit(t){const c=document.querySelector('#orbit');if(!c)return;const ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.fillStyle='#16130f';ctx.fillRect(0,0,w,h);ctx.beginPath();ctx.arc(w/2,h/2,10,0,6.28);ctx.fillStyle='#f0c56e';ctx.fill();planets.forEach((p,i)=>{ctx.beginPath();ctx.strokeStyle='rgba(243,234,223,.18)';ctx.arc(w/2,h/2,p.a,0,6.28);ctx.stroke();const ang=t*p.speed+i,x=w/2+Math.cos(ang)*p.a,y=h/2+Math.sin(ang)*p.a*.62;ctx.beginPath();ctx.fillStyle=p.color;ctx.arc(x,y,i===4?9:5,0,6.28);ctx.fill();});if(orbitOn)requestAnimationFrame(drawOrbit);}
requestAnimationFrame(drawOrbit);
document.querySelector('#orbitToggle').addEventListener('click',()=>{orbitOn=!orbitOn;if(orbitOn)requestAnimationFrame(drawOrbit);});
const loki={gp:0,hunger:40,happy:55,energy:70};function stage(gp){return gp>=500?'Adult':gp>=200?'Juvenile':gp>=50?'Hatchling':'Egg';}
function renderLoki(){document.querySelector('#lokiStage').textContent=stage(loki.gp)+' · '+loki.gp+' gp';document.querySelector('#hunger').style.width=loki.hunger+'%';document.querySelector('#happy').style.width=loki.happy+'%';document.querySelector('#energy').style.width=loki.energy+'%';}
function feed(kind){const gain=kind==='special'?25:kind==='tasty'?12:6;loki.gp+=gain;loki.hunger=Math.max(0,loki.hunger-gain);loki.happy=Math.min(100,loki.happy+8);loki.energy=Math.max(10,loki.energy-4);renderLoki();}
document.querySelectorAll('[data-feed]').forEach(b=>b.addEventListener('click',()=>feed(b.dataset.feed)));renderLoki();
const KEY='nlane-shift-log';function loadLog(){const items=JSON.parse(localStorage.getItem(KEY)||'[]');document.querySelector('#log').innerHTML=items.length?items.map(i=>'<div class="log-item"><strong>'+i.area+'</strong> · '+i.when+'<br>'+i.note+'</div>').join(''):'<div class="log-item">No calls yet. Notes stay in this browser only.</div>';}
document.querySelector('#logForm').addEventListener('submit',e=>{e.preventDefault();const items=JSON.parse(localStorage.getItem(KEY)||'[]');items.unshift({area:document.querySelector('#area').value,note:document.querySelector('#note').value,when:new Date().toLocaleString()});localStorage.setItem(KEY,JSON.stringify(items.slice(0,12)));e.target.reset();loadLog();});loadLog();
document.querySelector('#vform').addEventListener('input',voltageDrop);voltageDrop();
